require "sektor/parsers/id_parser"
require "sektor/parsers/title_parser"
require "sektor/parsers/time_parser"
require "sektor/parsers/artist_parser"
require "sektor/parsers/size_parser"
require "sektor/parsers/bitrate_parser"
require "sektor/parsers/link_parser"
require "sektor/parsers/track_parser"
